---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: FIXME - Project
description: FIXME
stability: prototype
strictProperties: true
type:
- object
definitions:
  id:
    description: unique identifier of project
    readOnly: true
    format: uuid
    type:
    - string
  name:
    description: unique name of project
    readOnly: true
    type:
    - string
  identity:
    anyOf:
    - "$ref": "/schemata/project#/definitions/id"
    - "$ref": "/schemata/project#/definitions/name"
  created_at:
    description: when project was created
    format: date-time
    type:
    - string
  updated_at:
    description: when project was updated
    format: date-time
    type:
    - string
links:
- description: Create a new project.
  href: "/projects"
  method: POST
  rel: create
  schema:
    properties: {}
    type:
    - object
  title: Create
- description: Delete an existing project.
  href: "/projects/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}"
  method: DELETE
  rel: destroy
  title: Delete
- description: Info for existing project.
  href: "/projects/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}"
  method: GET
  rel: self
  title: Info
- description: List existing projects.
  href: "/projects"
  method: GET
  rel: instances
  title: List
- description: Update an existing project.
  href: "/projects/{(%2Fschemata%2Fproject%23%2Fdefinitions%2Fidentity)}"
  method: PATCH
  rel: update
  schema:
    properties: {}
    type:
    - object
  title: Update
properties:
  created_at:
    "$ref": "/schemata/project#/definitions/created_at"
  id:
    "$ref": "/schemata/project#/definitions/id"
  name:
    "$ref": "/schemata/project#/definitions/name"
  updated_at:
    "$ref": "/schemata/project#/definitions/updated_at"
id: schemata/project
